format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$kotlin\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$directory
$character"""

command_timeout = 2000

[character]
error_symbol = "[✗](bold red)"
format = "$symbol "
success_symbol = "[➜](bold green)"

[time]
disabled = true
format = '[(\[$time\])]($style) '
style = "yellow"

[battery]

[[battery.display]]
style = "bold red"
threshold = 10

[[battery.display]]
style = "bold yellow"
threshold = 30

[directory]
format = "» Directory: [$path]($style)[$read_only]($read_only_style) "
style = "bold #F4A261"
truncation_symbol = "🏠 .../"

[package]
display_private = true

[aws]
disabled = true

[gcloud]
disabled = true
# symbol = "🌐 "
# format = 'on [$symbol$account(@$domain)(\[$project\])(\($region\))]($style) '
# format = 'on [$symbol(\[$project\])(\($region\))]($style) '

[nodejs]
format = "via [$symbol($version)]($style) "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
